### ISSUE TITLE
Deploying sample workspace into container fails -> ubuntu/20.04/prod focal InRelease is not signed

### ISSUE THREAD

**Issue by seantleonard** [Azure-Samples/azure-sql-library-app-blazor#7]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> open workspace in container after cloning locally.

### Any log messages given by the failure

> 5.146 W: GPG error: https://packages.microsoft.com/ubuntu/20.04/prod focal InRel
> ease: The following signatures couldn't be verified because the public key is no
> t available: NO_PUBKEY EB3E94ADBE1229CF
> 5.146 E: The repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal
> InRelease' is not signed.
> 5.148 ERROR: Feature "Docker (docker-outside-of-docker)" (ghcr.io/devcontainers/
> features/docker-outside-of-docker) failed to install! Look at the documentation
> at https://github.com/devcontainers/features/tree/main/src/docker-outside-of-doc
> ker for help troubleshooting this error.
> ------
> failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/docker-outsi
> de-of-docker_2 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-
> features/docker-outside-of-docker_2  && cd /tmp/dev-container-features/docker-ou
> tside-of-docker_2  && chmod +x ./devcontainer-features-install.sh  && ./devconta
> iner-features-install.sh  && rm -rf /tmp/dev-container-features/docker-outside-o
> f-docker_2" did not complete successfully: exit code: 100
> [29720 ms] Error: Command failed: docker-compose --project-name dab-library-sample_devcontainer -f c:\Users\x\Documents\Dev\dab-library-sample\.devcontainer\docker-compose.yml -f c:\Users\x\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.build-1719330020761.yml build
> [29721 ms]     at Km (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-containers-0.369.0\dist\spec-node\devContainersSpecCLI.js:429:525)
> [29721 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> [29722 ms]     at async QtA (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-containers-0.369.0\dist\spec-node\devContainersSpecCLI.js:429:2476)
> [29722 ms]     at async utA (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-containers-0.369.0\dist\spec-node\devContainersSpecCLI.js:409:3506)
> [29722 ms]     at async KtA (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-containers-0.369.0\dist\spec-node\devContainersSpecCLI.js:481:3865)
> [29723 ms]     at async eB (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-containers-0.369.0\dist\spec-node\devContainersSpecCLI.js:481:4807)
> [29723 ms]     at async hrA (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-containers-0.369.0\dist\spec-node\devContainersSpecCLI.js:661:13373)
> [29730 ms]     at async lrA (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-containers-0.369.0\dist\spec-node\devContainersSpecCLI.js:661:13114)
> [29752 ms] Exit code 1
> [29759 ms] Command failed: C:\Users\x\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-containers-0.369.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\x\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-eeed2085-a263-4254-b7e4-78600811aa1d1719330012456 --workspace-folder c:\Users\x\Documents\Dev\dab-library-sample --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\x\Documents\Dev\dab-library-sample --id-label devcontainer.config_file=c:\Users\x\Documents\Dev\dab-library-sample\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\x\Documents\Dev\dab-library-sample\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu-20.04\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-6a4551d5-dd40-4d05-9b11-4dc9793205f0.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
> [29759 ms] Exit code 1

### Expected/desired behavior
Container should deploy without error

### OS and Version?
Windows 11 using WSL2

### Versions
Sample from this repo commit: https://github.com/Azure-Samples/azure-sql-library-app-blazor/commit/0a1ba8c97744d887f209d95c7f932ddf0eb8b04c

### Additional info

looks like this has happened in past when signing keys expire and may need version bump in dockerfile:
- https://github.com/devcontainers/images/issues/370

**Comment by seantleonard** [comment]
I see that this setup script in the repo already includes the step to import microsoft signing keys: 
https://github.com/Azure-Samples/azure-sql-library-app-blazor/blob/0a1ba8c97744d887f209d95c7f932ddf0eb8b04c/.devcontainer/sql/installSQLtools.sh#L4-L6

Perhaps this issue fully stems from #9 because the scripts aren't executed due to DOS line endings when pulling repo onto windows instead of linux.
